//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ngubui_Project.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NgubuiEntities : DbContext
    {
        public NgubuiEntities()
            : base("name=NgubuiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BOOK_ROOM> BOOK_ROOM { get; set; }
        public virtual DbSet<ROOM_IMAGE> ROOM_IMAGE { get; set; }
        public virtual DbSet<ROOM_NAME> ROOM_NAME { get; set; }
        public virtual DbSet<ROOM_NAME_DETAIL> ROOM_NAME_DETAIL { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<USER_NAME> USER_NAME { get; set; }
        public virtual DbSet<USER_NAME_DETAIL> USER_NAME_DETAIL { get; set; }
        public virtual DbSet<WHISLIST_ROOM> WHISLIST_ROOM { get; set; }
    }
}
