//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ngubui_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ROOM_NAME_DETAIL
    {
        public int ID_Room { get; set; }
        [Required(ErrorMessage = "Bạn chưa chọn loại phòng!", AllowEmptyStrings = false)]
        public string LoaiPhong { get; set; }
        public Nullable<short> Khach { get; set; }
        public Nullable<short> SoPhongNgu { get; set; }
        public Nullable<short> SoGiuongNgu { get; set; }
        public string Wifi { get; set; }
        public string BaiXe { get; set; }
        public string ThucAn { get; set; }
        public string ThucUong { get; set; }
        public string NoiQuy { get; set; }
        public string MoTa { get; set; }
        [Required(ErrorMessage = "Bạn chưa nhập tiêu đề!", AllowEmptyStrings = false)]
        public string TieuDe { get; set; }
        [Required(ErrorMessage = "Bạn chưa nhập giá phòng!", AllowEmptyStrings = false)]
        public Nullable<int> GiaPhong { get; set; }
        [Required(ErrorMessage = "Bạn chưa chọn ảnh đại diện!", AllowEmptyStrings = false)]
        public byte[] AnhDaiDien { get; set; }
        [Required(ErrorMessage = "Bạn chưa nhập địa chỉ!", AllowEmptyStrings = false)]
        public string DiaChi { get; set; }
        [Required(ErrorMessage = "Bạn chưa chọn tọa độ!", AllowEmptyStrings = false)]
        public string ToaDo { get; set; }
        public Nullable<int> ID_User { get; set; }
        public string XetDuyet { get; set; }
 
        public byte[] Image1 { get; set; }

        public byte[] Image2 { get; set; }
 
        public byte[] Image3 { get; set; }

        public byte[] Image4 { get; set; }
   
        public byte[] Image5 { get; set; }
  
        public byte[] Image6 { get; set; }

        public byte[] Image7 { get; set; }

        public byte[] Image8 { get; set; }
     
        public byte[] Image9 { get; set; }
        public string Checkin { get; set; }
        public string Checkout { get; set; }
        public string SoKhach { get; set; }
        public virtual ROOM_IMAGE ROOM_IMAGE { get; set; }
        public virtual ROOM_NAME ROOM_NAME { get; set; }
    }
}
