//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ngubui_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROOM_NAME
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ROOM_NAME()
        {
            this.BOOK_ROOM = new HashSet<BOOK_ROOM>();
            this.WHISLIST_ROOM = new HashSet<WHISLIST_ROOM>();
        }
    
        public int ID_Room { get; set; }
        public Nullable<int> ID_User { get; set; }
        public string TrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOK_ROOM> BOOK_ROOM { get; set; }
        public virtual ROOM_NAME_DETAIL ROOM_NAME_DETAIL { get; set; }
        public virtual USER_NAME USER_NAME { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WHISLIST_ROOM> WHISLIST_ROOM { get; set; }
    }
}
