//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ngubui_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class USER_NAME
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER_NAME()
        {
            this.BOOK_ROOM = new HashSet<BOOK_ROOM>();
            this.ROOM_NAME = new HashSet<ROOM_NAME>();
            this.WHISLIST_ROOM = new HashSet<WHISLIST_ROOM>();
        }
    
        public int ID_User { get; set; }
        [Required(ErrorMessage = "Mời bạn nhập tên!", AllowEmptyStrings = false)]
        public string Ten { get; set; }
        [Required(ErrorMessage = "Mời bạn nhập họ!", AllowEmptyStrings = false)]
        public string Ho { get; set; }
        [Required(ErrorMessage = "Mời bạn nhập mail!", AllowEmptyStrings = false)]
        [RegularExpression(@"^([0-9a-zA-Z]([\+\-_\.][0-9a-zA-Z]+)*)+@(([0-9a-zA-Z][-\w]*[0-9a-zA-Z]*\.)+[a-zA-Z0-9]{2,3})$",
        ErrorMessage = "Nhập sai định dạng mail!")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Mời bạn nhập mật khẩu!", AllowEmptyStrings = false)]
        [DataType(System.ComponentModel.DataAnnotations.DataType.Password)]
        [StringLength(50, MinimumLength = 8, ErrorMessage = "Mật khẩu phải có ít nhất 8 ký tự.")]
        public string MatKhau { get; set; }
        [Compare("MatKhau", ErrorMessage = "Mật khẩu không trùng khớp!")]
        [DataType(System.ComponentModel.DataAnnotations.DataType.Password)]
        public string MatKhauConfirm { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOK_ROOM> BOOK_ROOM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ROOM_NAME> ROOM_NAME { get; set; }
        public virtual USER_NAME_DETAIL USER_NAME_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WHISLIST_ROOM> WHISLIST_ROOM { get; set; }
    }
}
